import 'package:commander_orchestrator/src/intent/prompt_intent.dart';
import 'package:commander_orchestrator/src/models/command_models.dart';
import 'package:commander_orchestrator/src/models/repo_context_bundle.dart';
import 'package:cursor_api_agents/cursor_api_agents.dart';

/// Builds API requests and enriched prompts from context bundles.
class PromptBuilder {
  const PromptBuilder({this.maxBriefingChars = 4000});

  final int maxBriefingChars;

  BuiltCommand build(CommandInput input, RepoContextBundle context) {
    final intent = PromptIntent.analyze(input.userPrompt);
    final briefing = _buildBriefing(input, context, intent);
    final enriched = _wrapPrompt(input.userPrompt, briefing, input.locale);

    final usePr = input.prUrl ?? context.prUrl;
    final mode = input.mode ??
        (intent.suggestPlanMode ? 'plan' : 'agent');
    final autoPr = input.autoCreatePr ?? intent.wantsPr;

    final request = CreateAgentRequest.singleRepo(
      repoUrl: context.repoUrl,
      prompt: enriched,
      startingRef: usePr != null ? null : context.resolvedBranch,
      prUrl: usePr,
      images: input.images,
      modelId: input.modelId,
      modelParams: input.modelParams,
      mode: mode,
      autoCreatePr: autoPr,
      workOnCurrentBranch: input.workOnCurrentBranch,
      env: input.cloudEnv,
      envVars: input.envVars,
    );

    return BuiltCommand(
      request: request,
      userPrompt: input.userPrompt,
      enrichedPrompt: enriched,
      contextSummary: briefing,
      resolvedMode: mode,
      resolvedBranch: context.resolvedBranch,
      resolvedPrUrl: usePr,
    );
  }

  CreateRunRequest buildFollowUp(CommandInput input, RepoContextBundle? context) {
    final briefing = context != null
        ? _buildBriefing(input, context, PromptIntent.analyze(input.userPrompt))
        : '';
    final enriched = briefing.isEmpty
        ? input.userPrompt
        : _wrapPrompt(input.userPrompt, briefing, input.locale);

    return CreateRunRequest(
      prompt: enriched,
      images: input.images,
      mode: input.mode,
    );
  }

  String _buildBriefing(
    CommandInput input,
    RepoContextBundle ctx,
    PromptIntent intent,
  ) {
    final lines = <String>[
      '- Repository: ${ctx.fullName}',
      '- Branch: ${ctx.resolvedBranch}',
      if (ctx.defaultBranch != null) '- Default branch: ${ctx.defaultBranch}',
      if (ctx.projectHints.isNotEmpty)
        '- Stack: ${ctx.projectHints.join(', ')}',
      if (ctx.prUrl != null)
        '- Open PR: #${ctx.prNumber ?? '?'} "${ctx.prTitle ?? ''}" (${ctx.prUrl})',
      if (ctx.ciState != null) '- CI status: ${ctx.ciState}',
      if (ctx.failingChecks != null && ctx.failingChecks!.isNotEmpty)
        '- Failing checks: ${ctx.failingChecks!.join(', ')}',
      if (ctx.recentCommits.isNotEmpty)
        '- Recent commits: ${ctx.recentCommits.map((c) => '${c.shortSha} ${c.message}').join('; ')}',
      if (ctx.agentsMdPresent) '- AGENTS.md: present in repo',
      if (ctx.environmentJsonPresent)
        '- .cursor/environment.json: present',
      if (ctx.readmeExcerpt != null && intent.wantsExplain)
        '- README excerpt:\n${ctx.readmeExcerpt}',
    ];

    var text = lines.join('\n');
    if (text.length > maxBriefingChars) {
      text = '${text.substring(0, maxBriefingChars)}…';
    }
    return text;
  }

  String _wrapPrompt(String userPrompt, String briefing, String locale) {
    final header = locale.startsWith('nl')
        ? '## Context (automatisch door Cursor Commander)'
        : '## Context (auto-generated by Cursor Commander)';
    final task = locale.startsWith('nl') ? '## Opdracht' : '## Task';
    final notes = locale.startsWith('nl')
        ? '## Richtlijnen\n- Volg AGENTS.md en .cursor/rules in de repo indien aanwezig.\n- Gebruik de cloud-omgeving en tools om de repo te verkennen voordat je grote wijzigingen maakt.'
        : '## Guidelines\n- Follow AGENTS.md and .cursor/rules in the repo when present.\n- Explore the repo with tools before large changes.';

    return '$header\n$briefing\n\n$task\n$userPrompt\n\n$notes';
  }
}

class BuiltCommand {
  const BuiltCommand({
    required this.request,
    required this.userPrompt,
    required this.enrichedPrompt,
    required this.contextSummary,
    required this.resolvedMode,
    required this.resolvedBranch,
    this.resolvedPrUrl,
  });

  final CreateAgentRequest request;
  final String userPrompt;
  final String enrichedPrompt;
  final String contextSummary;
  final String resolvedMode;
  final String resolvedBranch;
  final String? resolvedPrUrl;
}
