include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_return: error
    dead_code: warning
    unused_import: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - avoid_print
    - prefer_final_locals
    - prefer_const_constructors
    - prefer_const_declarations
    - require_trailing_commas
    - sort_pub_dependencies
    - use_super_parameters
    - always_use_package_imports
